### ISSUE TITLE
When trying to send email

### ISSUE THREAD

**Issue by mistralol** [fardog/nodemailer-cli#4]
Command lines that fail are as followings

./bin/nodemailer.js x@example.com y@example.com "Hello World" -j "Testing" -n
./bin/nodemailer.js x@example.com y@example.com "Hello World" -j "Testing"

crypto.js:91
  this._handle.init(hmac, toBuf(key));
               ^

TypeError: Key must be a buffer
    at TypeError (native)
    at new Hmac (crypto.js:91:16)
    at Object.Hmac (crypto.js:89:12)
    at SMTPConnection._actionAUTH_CRAM_MD5 (/home/james/tmp/x/nodemailer-cli/node_modules/smtp-connection/src/smtp-connection.js:802:27)
    at SMTPConnection.<anonymous> (/home/james/tmp/x/nodemailer-cli/node_modules/smtp-connection/src/smtp-connection.js:249:22)
    at SMTPConnection._processResponse (/home/james/tmp/x/nodemailer-cli/node_modules/smtp-connection/src/smtp-connection.js:516:16)
    at SMTPConnection._onData (/home/james/tmp/x/nodemailer-cli/node_modules/smtp-connection/src/smtp-connection.js:353:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)

**Comment by fardog** [comment]
This utility hasn't been updated in over two years; I'm wondering if it's an issue with recent node versions. Can you let me know what version of Node.js you are on? (to see this, run `node --version`.) I personally don't use this utility any more, but will see if it's an easy fix.

**Comment by fardog** [comment]
…and actually, are you specifying a username, password, and server? it's not going to work without those.

**Comment by mistralol** [comment]
Node version is v6.7.0. It will run fine with the later version of nodemailer just not with the cli.

It does not seem to matter if I specific a server or not. I assume it defaults to localhost but I tried passing -s localhost to it anyway. The username / password isn't required for a localhost relay.

But I tried it anyway with a real server with server / username / password on the command line. Instead I get an auth rejected for valid credentials with

{ Error: Invalid login sequence while waiting for "235": 535 5.7.0 authentication failed
    at SMTPConnection._formatError (/home/james/tmp/x/nodemailer-cli/node_modules/smtp-connection/src/smtp-connection.js:384:15)
    at SMTPConnection._actionAUTH_CRAM_MD5_PASS (/home/james/tmp/x/nodemailer-cli/node_modules/smtp-connection/src/smtp-connection.js:826:30)
    at SMTPConnection.<anonymous> (/home/james/tmp/x/nodemailer-cli/node_modules/smtp-connection/src/smtp-connection.js:810:14)
    at SMTPConnection._processResponse (/home/james/tmp/x/nodemailer-cli/node_modules/smtp-connection/src/smtp-connection.js:516:16)
    at SMTPConnection._onData (/home/james/tmp/x/nodemailer-cli/node_modules/smtp-connection/src/smtp-connection.js:353:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
  code: 'EAUTH',
  response: '535 5.7.0 authentication failed',
  responseCode: 535 }

If you don't use / maintain this utility any more or don't have an interest in keeping it up to date. I might volunteer take it off your hands for you if you like.

**Comment by fardog** [comment]
Sure, I'd happily add you as a contributor on github and npm if you have the time. If you have a fix please file a pull request, and I'll add you afterwards. Thanks tons! I really appreciate the offer.

**Comment by mistralol** [comment]
I sent a pull request which fixes my immediate issue. Which is nodemailer trying to push undefined as a username / password.

The deeper issue I also have with another server is that it won't support MD5 auth as the password hashes are not stored that way and wants a PLAIN auth method used instead since smtp doesn't have the hash method and most client's won't support it either. But its is still ok to use plain when TLS/SSL is in use since its encrypted anyway.

So more pull requests to probably follow. Kept the first one small to see how it goes..

Also there is a bunch of argument changes for nodemailer for ssl / tls options that will need fixed when updating the package to the later version. Will probably tackle this issue next.

**Comment by fardog** [comment]
Awesome; merged that and will close this issue. Will be publishing that as a patch version shortly. Also, sent you an invite as a collaborator on the project. Big thanks!

**Comment by mistralol** [comment]
Are you happy for me to commit directly to the repo. Or do you want me
to keep sending pull requests or I can work on a branch instead if you
would preferred.

I was going to bring the deps up to date and also fix the other tls /
ssl issues over the next few days.

I will of course try not to break anything!

**Comment by fardog** [comment]
@mistralol please submit pull requests; i'll always make sure to get reviews on them within a few days. Travis CI is running on the repository so that way we'll see failures on a PR rather than having them hit master.

When you do the dependency updates, it'd be great to get the latest node versions added to the Travis config so we can ensure things are working on newer node (right now only 0.10 is tested because of the age of this util). Thank you!

**Comment by fardog** [comment]
(oh, i will say though that i always just commit changelog updates to the README and version bumps directly to master, since the `npm` tooling makes that convenient; so def feel free to do that)
